language: php
php:
  - "5.6"
  - "7.0"
  - "hhvm"

before_script:
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install

script: 
  - php vendor/bin/phpunit --coverage-text

matrix:
     allow_failures:
         - php: "hhvm"
branches:
  only:
    - master
 
